import { createSlice, PayloadAction } from '@reduxjs/toolkit'

interface LanguageState {
  currentLanguage: string
  translations: Record<string, Record<string, string>>
}

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.missions': 'Missions',
    'nav.badges': 'Badges',
    'nav.leaderboard': 'Leaderboard',
    'nav.profile': 'Profile',
    // Dashboard
    'dashboard.volunteerHours': 'Volunteer Hours Completed',
    'dashboard.growth': 'month over month',
    'dashboard.viewBadges': 'View Badges & Milestones',
    'dashboard.hoursStatement': 'Volunteer Hours Statement',
    'dashboard.leaderboard': 'Leaderboard',
    'dashboard.viewAll': 'View All',
    'dashboard.you': 'You',
    'dashboard.hours': 'hours',
    'dashboard.dataFor': 'Data for',
    // Stats
    'stats.totalHours': 'Total Hours',
    'stats.projects': 'Projects Completed',
    'stats.organizations': 'Organizations Helped',
    'stats.rating': 'Average Rating',
    'stats.thisMonth': 'this month',
    // Badges
    'badges.title': 'Badges & Milestones',
    'badges.description': 'Earn certificates, medals, and milestones based on your volunteer hours. Apply for official recognition from partner organizations.',
    'badges.earned': 'Badges Earned',
    'badges.totalHours': 'Total Hours',
    'badges.nextBadge': 'Hours to Next Badge',
    'badges.allEarned': 'All Badges Earned!',
    'badges.all': 'All Badges',
    'badges.milestones': 'Milestones',
    'badges.certificates': 'Certificates',
    'badges.medals': 'Medals',
    'badges.earnedOn': 'Earned on',
    'badges.applyCertificate': 'Apply for Certificate',
    'badges.claimMedal': 'Claim Medal',
    'badges.moreHours': 'more hours needed',
    // Missions
    'missions.title': 'Available Missions',
    'missions.subtitle': 'Join volunteer missions and make a positive impact in your community',
    'missions.all': 'All Missions',
    'missions.environment': 'Environment',
    'missions.community': 'Community',
    'missions.healthcare': 'Healthcare',
    'missions.education': 'Education',
    'missions.animals': 'Animals',
    'missions.join': 'Join Mission',
    'missions.leave': 'Leave Mission',
    'missions.participants': 'participants',
    'missions.region': 'Region',
    'missions.allRegions': 'All Regions',
    'missions.difficulty.easy': 'Easy',
    'missions.difficulty.medium': 'Medium',
    'missions.difficulty.hard': 'Hard',
    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email Address',
    'profile.phone': 'Phone Number',
    'profile.city': 'City / Residency',
    'profile.language': 'Language Settings',
    'profile.interests': 'Volunteer Interests',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.back': 'Back',
    // Auth
    'auth.title': 'Sign in to KindWorld',
    'auth.subtitle': 'Transform Kindness into Impact',
    'auth.chooseAccount': 'Choose your account type:',
    'auth.signInWith': 'Sign in to KindWorld with Gmail',
    'auth.signingIn': 'Signing in...',
    'auth.roleStudent': 'Sign-in by Student',
    'auth.roleStudentDesc': "I'm a student who wants to volunteer and track my hours",
    'auth.roleCompany': 'Sign-in by Company',
    'auth.roleCompanyDesc': 'I represent a company that supports volunteer programs',
    'auth.roleNGO': 'Sign-in by NGO',
    'auth.roleNGODesc': "I'm an NGO that creates missions and verifies volunteer work",
    'auth.demoMode': 'Demo Mode',
    'auth.demoInstruction': 'Click the button above to sign in as a',
    'auth.successTitle': 'Authentication Successful! 🎉',
    'auth.redirecting': 'Redirecting to your',
    'auth.dashboard': 'dashboard',
    'auth.student': 'student',
    'auth.company': 'company',
    'auth.ngo': 'NGO',
    'auth.termsAgree': 'By continuing, you agree to our',
    'auth.termsOfService': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacyPolicy': 'Privacy Policy'
  },
  id: {
    // Navigation
    'nav.home': 'Beranda',
    'nav.missions': 'Misi',
    'nav.badges': 'Lencana',
    'nav.leaderboard': 'Papan Peringkat',
    'nav.profile': 'Profil',
    // Dashboard
    'dashboard.volunteerHours': 'Jam Sukarela Selesai',
    'dashboard.growth': 'bulan ke bulan',
    'dashboard.viewBadges': 'Lihat Lencana & Pencapaian',
    'dashboard.hoursStatement': 'Laporan Jam Sukarela',
    'dashboard.leaderboard': 'Papan Peringkat',
    'dashboard.viewAll': 'Lihat Semua',
    'dashboard.you': 'Anda',
    'dashboard.hours': 'jam',
    'dashboard.dataFor': 'Data untuk',
    // Stats
    'stats.totalHours': 'Total Jam',
    'stats.projects': 'Proyek Selesai',
    'stats.organizations': 'Organisasi Dibantu',
    'stats.rating': 'Rating Rata-rata',
    'stats.thisMonth': 'bulan ini',
    // Badges
    'badges.title': 'Lencana & Pencapaian',
    'badges.description': 'Dapatkan sertifikat, medali, dan pencapaian berdasarkan jam sukarela Anda. Ajukan pengakuan resmi dari organisasi mitra.',
    'badges.earned': 'Lencana Diperoleh',
    'badges.totalHours': 'Total Jam',
    'badges.nextBadge': 'Jam ke Lencana Berikutnya',
    'badges.allEarned': 'Semua Lencana Diperoleh!',
    'badges.all': 'Semua Lencana',
    'badges.milestones': 'Pencapaian',
    'badges.certificates': 'Sertifikat',
    'badges.medals': 'Medali',
    'badges.earnedOn': 'Diperoleh pada',
    'badges.applyCertificate': 'Ajukan Sertifikat',
    'badges.claimMedal': 'Klaim Medali',
    'badges.moreHours': 'jam lagi diperlukan',
    // Missions
    'missions.title': 'Kegiatan Tersedia',
    'missions.subtitle': 'Bergabunglah dengan kegiatan relawan dan ciptakan dampak positif di komunitas Anda',
    'missions.all': 'Semua Kegiatan',
    'missions.environment': 'Lingkungan',
    'missions.community': 'Komunitas',
    'missions.healthcare': 'Kesehatan',
    'missions.education': 'Pendidikan',
    'missions.animals': 'Satwa',
    'missions.join': 'Ikuti Kegiatan',
    'missions.leave': 'Keluar dari Kegiatan',
    'missions.participants': 'peserta',
    'missions.region': 'Wilayah',
    'missions.allRegions': 'Semua Wilayah',
    'missions.difficulty.easy': 'Mudah',
    'missions.difficulty.medium': 'Sedang',
    'missions.difficulty.hard': 'Sulit',
    // Profile
    'profile.title': 'Profil',
    'profile.edit': 'Edit Profil',
    'profile.save': 'Simpan Perubahan',
    'profile.cancel': 'Batal',
    'profile.personalInfo': 'Informasi Pribadi',
    'profile.fullName': 'Nama Lengkap',
    'profile.email': 'Alamat Email',
    'profile.phone': 'Nomor Telepon',
    'profile.city': 'Kota Tempat Tinggal',
    'profile.language': 'Pengaturan Bahasa',
    'profile.interests': 'Minat Kerelawanan',
    // Common
    'common.loading': 'Memuat...',
    'common.error': 'Terjadi kesalahan',
    'common.retry': 'Coba Lagi',
    'common.close': 'Tutup',
    'common.back': 'Kembali',
    // Auth
    'auth.title': 'Masuk ke KindWorld',
    'auth.subtitle': 'Wujudkan Kebaikan Menjadi Dampak Nyata',
    'auth.chooseAccount': 'Pilih jenis akun Anda:',
    'auth.signInWith': 'Masuk ke KindWorld dengan Gmail',
    'auth.signingIn': 'Sedang masuk...',
    'auth.roleStudent': 'Masuk sebagai Pelajar',
    'auth.roleStudentDesc': 'Saya adalah pelajar yang ingin menjadi relawan dan melacak jam saya',
    'auth.roleCompany': 'Masuk sebagai Perusahaan',
    'auth.roleCompanyDesc': 'Saya mewakili perusahaan yang mendukung program relawan',
    'auth.roleNGO': 'Masuk sebagai NGO',
    'auth.roleNGODesc': 'Saya adalah NGO yang membuat misi dan memverifikasi pekerjaan relawan',
    'auth.demoMode': 'Mode Demo',
    'auth.demoInstruction': 'Klik tombol di atas untuk masuk sebagai',
    'auth.successTitle': 'Autentikasi Berhasil! 🎉',
    'auth.redirecting': 'Mengarahkan ke',
    'auth.dashboard': 'dasbor',
    'auth.student': 'pelajar',
    'auth.company': 'perusahaan',
    'auth.ngo': 'NGO',
    'auth.termsAgree': 'Dengan melanjutkan, Anda menyetujui',
    'auth.termsOfService': 'Ketentuan Layanan',
    'auth.and': 'dan',
    'auth.privacyPolicy': 'Kebijakan Privasi'
  },
  'zh-cn': {
    // Navigation
    'nav.home': '首页',
    'nav.missions': '任务',
    'nav.badges': '徽章',
    'nav.leaderboard': '排行榜',
    'nav.profile': '个人资料',
    // Dashboard
    'dashboard.volunteerHours': '志愿服务小时完成',
    'dashboard.growth': '月环比',
    'dashboard.viewBadges': '查看徽章和里程碑',
    'dashboard.hoursStatement': '志愿服务小时报表',
    'dashboard.leaderboard': '排行榜',
    'dashboard.viewAll': '查看全部',
    'dashboard.you': '您',
    'dashboard.hours': '小时',
    'dashboard.dataFor': '数据',
    // Stats
    'stats.totalHours': '总小时数',
    'stats.projects': '完成项目',
    'stats.organizations': '帮助组织',
    'stats.rating': '平均评分',
    'stats.thisMonth': '本月',
    // Badges
    'badges.title': '徽章和里程碑',
    'badges.description': '根据您的志愿服务小时获得证书、奖章和里程碑。申请合作组织的官方认可。',
    'badges.earned': '获得徽章',
    'badges.totalHours': '总小时数',
    'badges.nextBadge': '距离下一个徽章的小时数',
    'badges.allEarned': '所有徽章已获得！',
    'badges.all': '所有徽章',
    'badges.milestones': '里程碑',
    'badges.certificates': '证书',
    'badges.medals': '奖章',
    'badges.earnedOn': '获得于',
    'badges.applyCertificate': '申请证书',
    'badges.claimMedal': '领取奖章',
    'badges.moreHours': '还需要更多小时',
    // Missions
    'missions.title': '可用任务',
    'missions.subtitle': '加入志愿任务，为您的社区创造积极影响',
    'missions.all': '所有任务',
    'missions.environment': '环境',
    'missions.community': '社区',
    'missions.healthcare': '医疗',
    'missions.education': '教育',
    'missions.animals': '动物',
    'missions.join': '加入任务',
    'missions.leave': '退出任务',
    'missions.participants': '参与者',
    'missions.region': '地区',
    'missions.allRegions': '所有地区',
    'missions.difficulty.easy': '简单',
    'missions.difficulty.medium': '中等',
    'missions.difficulty.hard': '困难',
    // Profile
    'profile.title': '个人资料',
    'profile.edit': '编辑资料',
    'profile.save': '保存更改',
    'profile.cancel': '取消',
    'profile.personalInfo': '个人信息',
    'profile.fullName': '全名',
    'profile.email': '邮箱地址',
    'profile.phone': '电话号码',
    'profile.city': '城市/居住地',
    'profile.language': '语言设置',
    'profile.interests': '志愿兴趣',
    // Common
    'common.loading': '加载中...',
    'common.error': '发生错误',
    'common.retry': '重试',
    'common.close': '关闭',
    'common.back': '返回',
    // Auth
    'auth.title': '登录 KindWorld',
    'auth.subtitle': '将善意转化为影响力',
    'auth.chooseAccount': '选择您的账户类型：',
    'auth.signInWith': '使用 Gmail 登录 KindWorld',
    'auth.signingIn': '登录中...',
    'auth.roleStudent': '学生登录',
    'auth.roleStudentDesc': '我是一名想要志愿服务并记录时间的学生',
    'auth.roleCompany': '公司登录',
    'auth.roleCompanyDesc': '我代表支持志愿者项目的公司',
    'auth.roleNGO': 'NGO登录',
    'auth.roleNGODesc': '我是一个创建任务并验证志愿者工作的NGO',
    'auth.demoMode': '演示模式',
    'auth.demoInstruction': '点击上方按钮以登录为',
    'auth.successTitle': '验证成功！🎉',
    'auth.redirecting': '正在跳转到',
    'auth.dashboard': '仪表板',
    'auth.student': '学生',
    'auth.company': '公司',
    'auth.ngo': 'NGO',
    'auth.termsAgree': '继续即表示您同意我们的',
    'auth.termsOfService': '服务条款',
    'auth.and': '和',
    'auth.privacyPolicy': '隐私政策'
  },
  'zh-tw': {
    // Navigation
    'nav.home': '首頁',
    'nav.missions': '任務',
    'nav.badges': '徽章',
    'nav.leaderboard': '排行榜',
    'nav.profile': '個人資料',
    // Dashboard
    'dashboard.volunteerHours': '志願服務小時完成',
    'dashboard.growth': '月環比',
    'dashboard.viewBadges': '查看徽章和里程碑',
    'dashboard.hoursStatement': '志願服務小時報表',
    'dashboard.leaderboard': '排行榜',
    'dashboard.viewAll': '查看全部',
    'dashboard.you': '您',
    'dashboard.hours': '小時',
    'dashboard.dataFor': '資料',
    // Stats
    'stats.totalHours': '總小時數',
    'stats.projects': '完成項目',
    'stats.organizations': '幫助組織',
    'stats.rating': '平均評分',
    'stats.thisMonth': '本月',
    // Badges
    'badges.title': '徽章和里程碑',
    'badges.description': '根據您的志願服務小時獲得證書、獎章和里程碑。申請合作組織的官方認可。',
    'badges.earned': '獲得徽章',
    'badges.totalHours': '總小時數',
    'badges.nextBadge': '距離下一個徽章的小時數',
    'badges.allEarned': '所有徽章已獲得！',
    'badges.all': '所有徽章',
    'badges.milestones': '里程碑',
    'badges.certificates': '證書',
    'badges.medals': '獎章',
    'badges.earnedOn': '獲得於',
    'badges.applyCertificate': '申請證書',
    'badges.claimMedal': '領取獎章',
    'badges.moreHours': '還需要更多小時',
    // Missions
    'missions.title': '可用任務',
    'missions.subtitle': '加入志願任務，為您的社區創造積極影響',
    'missions.all': '所有任務',
    'missions.environment': '環境',
    'missions.community': '社區',
    'missions.healthcare': '醫療',
    'missions.education': '教育',
    'missions.animals': '動物',
    'missions.join': '加入任務',
    'missions.leave': '退出任務',
    'missions.participants': '參與者',
    'missions.region': '地區',
    'missions.allRegions': '所有地區',
    'missions.difficulty.easy': '簡單',
    'missions.difficulty.medium': '中等',
    'missions.difficulty.hard': '困難',
    // Profile
    'profile.title': '個人資料',
    'profile.edit': '編輯資料',
    'profile.save': '儲存變更',
    'profile.cancel': '取消',
    'profile.personalInfo': '個人資訊',
    'profile.fullName': '全名',
    'profile.email': '電子郵件地址',
    'profile.phone': '電話號碼',
    'profile.city': '城市/居住地',
    'profile.language': '語言設定',
    'profile.interests': '志願興趣',
    // Common
    'common.loading': '載入中...',
    'common.error': '發生錯誤',
    'common.retry': '重試',
    'common.close': '關閉',
    'common.back': '返回',
    // Auth
    'auth.title': '登入 KindWorld',
    'auth.subtitle': '將善意轉化為影響力',
    'auth.chooseAccount': '選擇您的帳戶類型：',
    'auth.signInWith': '使用 Gmail 登入 KindWorld',
    'auth.signingIn': '登入中...',
    'auth.roleStudent': '學生登入',
    'auth.roleStudentDesc': '我是一名想要志願服務並記錄時間的學生',
    'auth.roleCompany': '公司登入',
    'auth.roleCompanyDesc': '我代表支持志願者項目的公司',
    'auth.roleNGO': 'NGO登入',
    'auth.roleNGODesc': '我是一個創建任務並驗證志願者工作的NGO',
    'auth.demoMode': '演示模式',
    'auth.demoInstruction': '點擊上方按鈕以登入為',
    'auth.successTitle': '驗證成功！🎉',
    'auth.redirecting': '正在跳轉到',
    'auth.dashboard': '儀表板',
    'auth.student': '學生',
    'auth.company': '公司',
    'auth.ngo': 'NGO',
    'auth.termsAgree': '繼續即表示您同意我們的',
    'auth.termsOfService': '服務條款',
    'auth.and': '和',
    'auth.privacyPolicy': '隱私政策'
  },
  th: {
    // Navigation
    'nav.home': 'หน้าแรก',
    'nav.missions': 'ภารกิจ',
    'nav.badges': 'เหรียญตรา',
    'nav.leaderboard': 'กระดานผู้นำ',
    'nav.profile': 'โปรไฟล์',
    // Dashboard
    'dashboard.volunteerHours': 'ชั่วโมงอาสาสมัครที่เสร็จสิ้น',
    'dashboard.growth': 'เทียบกับเดือนที่แล้ว',
    'dashboard.viewBadges': 'ดูเหรียญตราและความสำเร็จ',
    'dashboard.hoursStatement': 'รายงานชั่วโมงอาสาสมัคร',
    'dashboard.leaderboard': 'กระดานผู้นำ',
    'dashboard.viewAll': 'ดูทั้งหมด',
    'dashboard.you': 'คุณ',
    'dashboard.hours': 'ชั่วโมง',
    'dashboard.dataFor': 'ข้อมูลสำหรับ',
    // Stats
    'stats.totalHours': 'ชั่วโมงทั้งหมด',
    'stats.projects': 'โครงการที่เสร็จสิ้น',
    'stats.organizations': 'องค์กรที่ช่วยเหลือ',
    'stats.rating': 'คะแนนเฉลี่ย',
    'stats.thisMonth': 'เดือนนี้',
    // Badges
    'badges.title': 'เหรียญตราและความสำเร็จ',
    'badges.description': 'รับใบรับรอง เหรียญ และความสำเร็จตามชั่วโมงอาสาสมัครของคุณ สมัครรับการรับรองอย่างเป็นทางการจากองค์กรพันธมิตร',
    'badges.earned': 'เหรียญตราที่ได้รับ',
    'badges.totalHours': 'ชั่วโมงทั้งหมด',
    'badges.nextBadge': 'ชั่วโมงถึงเหรียญตราถัดไป',
    'badges.allEarned': 'ได้รับเหรียญตราทั้งหมดแล้ว!',
    'badges.all': 'เหรียญตราทั้งหมด',
    'badges.milestones': 'ความสำเร็จ',
    'badges.certificates': 'ใบรับรอง',
    'badges.medals': 'เหรียญ',
    'badges.earnedOn': 'ได้รับเมื่อ',
    'badges.applyCertificate': 'สมัครใบรับรอง',
    'badges.claimMedal': 'รับเหรียญ',
    'badges.moreHours': 'ต้องการชั่วโมงเพิ่มเติม',
    // Missions
    'missions.title': 'ภารกิจที่มีอยู่',
    'missions.subtitle': 'เข้าร่วมภารกิจอาสาสมัครและสร้างผลกระทบเชิงบวกในชุมชนของคุณ',
    'missions.all': 'ภารกิจทั้งหมด',
    'missions.environment': 'สิ่งแวดล้อม',
    'missions.community': 'ชุมชน',
    'missions.healthcare': 'สุขภาพ',
    'missions.education': 'การศึกษา',
    'missions.animals': 'สัตว์',
    'missions.join': 'เข้าร่วมภารกิจ',
    'missions.leave': 'ออกจากภารกิจ',
    'missions.participants': 'ผู้เข้าร่วม',
    'missions.region': 'ภูมิภาค',
    'missions.allRegions': 'ทุกภูมิภาค',
    'missions.difficulty.easy': 'ง่าย',
    'missions.difficulty.medium': 'ปานกลาง',
    'missions.difficulty.hard': 'ยาก',
    // Profile
    'profile.title': 'โปรไฟล์',
    'profile.edit': 'แก้ไขโปรไฟล์',
    'profile.save': 'บันทึกการเปลี่ยนแปลง',
    'profile.cancel': 'ยกเลิก',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.fullName': 'ชื่อเต็ม',
    'profile.email': 'ที่อยู่อีเมล',
    'profile.phone': 'หมายเลขโทรศัพท์',
    'profile.city': 'เมือง/ที่อยู่',
    'profile.language': 'การตั้งค่าภาษา',
    'profile.interests': 'ความสนใจในการเป็นอาสาสมัคร',
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'เกิดข้อผิดพลาด',
    'common.retry': 'ลองอีกครั้ง',
    'common.close': 'ปิด',
    'common.back': 'กลับ',
    // Auth
    'auth.title': 'เข้าสู่ระบบ KindWorld',
    'auth.subtitle': 'เปลี่ยนความเมตตาเป็นผลกระทบ',
    'auth.chooseAccount': 'เลือกประเภทบัญชีของคุณ:',
    'auth.signInWith': 'เข้าสู่ระบบ KindWorld ด้วย Gmail',
    'auth.signingIn': 'กำลังเข้าสู่ระบบ...',
    'auth.roleStudent': 'เข้าสู่ระบบเป็นนักศึกษา',
    'auth.roleStudentDesc': 'ฉันเป็นนักศึกษาที่ต้องการเป็นอาสาสมัครและติดตามชั่วโมงของฉัน',
    'auth.roleCompany': 'เข้าสู่ระบบเป็นบริษัท',
    'auth.roleCompanyDesc': 'ฉันเป็นตัวแทนบริษัทที่สนับสนุนโปรแกรมอาสาสมัคร',
    'auth.roleNGO': 'เข้าสู่ระบบเป็น NGO',
    'auth.roleNGODesc': 'ฉันเป็น NGO ที่สร้างภารกิจและตรวจสอบงานอาสาสมัคร',
    'auth.demoMode': 'โหมดทดลอง',
    'auth.demoInstruction': 'คลิกปุ่มด้านบนเพื่อเข้าสู่ระบบเป็น',
    'auth.successTitle': 'ยืนยันตัวตนสำเร็จ! 🎉',
    'auth.redirecting': 'กำลังนำไปยัง',
    'auth.dashboard': 'แดชบอร์ด',
    'auth.student': 'นักศึกษา',
    'auth.company': 'บริษัท',
    'auth.ngo': 'NGO',
    'auth.termsAgree': 'ด้วยการดำเนินการต่อ คุณตกลงยอมรับ',
    'auth.termsOfService': 'ข้อกำหนดการใช้บริการ',
    'auth.and': 'และ',
    'auth.privacyPolicy': 'นโยบายความเป็นส่วนตัว'
  },
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.missions': 'Nhiệm vụ',
    'nav.badges': 'Huy hiệu',
    'nav.leaderboard': 'Bảng xếp hạng',
    'nav.profile': 'Hồ sơ',
    // Dashboard
    'dashboard.volunteerHours': 'Giờ tình nguyện đã hoàn thành',
    'dashboard.growth': 'so với tháng trước',
    'dashboard.viewBadges': 'Xem huy hiệu & thành tích',
    'dashboard.hoursStatement': 'Báo cáo giờ tình nguyện',
    'dashboard.leaderboard': 'Bảng xếp hạng',
    'dashboard.viewAll': 'Xem tất cả',
    'dashboard.you': 'Bạn',
    'dashboard.hours': 'giờ',
    'dashboard.dataFor': 'Dữ liệu cho',
    // Stats
    'stats.totalHours': 'Tổng số giờ',
    'stats.projects': 'Dự án hoàn thành',
    'stats.organizations': 'Tổ chức đã giúp',
    'stats.rating': 'Đánh giá trung bình',
    'stats.thisMonth': 'tháng này',
    // Badges
    'badges.title': 'Huy hiệu & Thành tích',
    'badges.description': 'Nhận chứng chỉ, huy chương và thành tích dựa trên giờ tình nguyện của bạn. Đăng ký công nhận chính thức từ các tổ chức đối tác.',
    'badges.earned': 'Huy hiệu đã nhận',
    'badges.totalHours': 'Tổng số giờ',
    'badges.nextBadge': 'Giờ đến huy hiệu tiếp theo',
    'badges.allEarned': 'Đã nhận tất cả huy hiệu!',
    'badges.all': 'Tất cả huy hiệu',
    'badges.milestones': 'Cột mốc',
    'badges.certificates': 'Chứng chỉ',
    'badges.medals': 'Huy chương',
    'badges.earnedOn': 'Nhận vào',
    'badges.applyCertificate': 'Đăng ký chứng chỉ',
    'badges.claimMedal': 'Nhận huy chương',
    'badges.moreHours': 'cần thêm giờ',
    // Missions
    'missions.title': 'Nhiệm vụ có sẵn',
    'missions.subtitle': 'Tham gia các nhiệm vụ tình nguyện và tạo tác động tích cực trong cộng đồng của bạn',
    'missions.all': 'Tất cả nhiệm vụ',
    'missions.environment': 'Môi trường',
    'missions.community': 'Cộng đồng',
    'missions.healthcare': 'Y tế',
    'missions.education': 'Giáo dục',
    'missions.animals': 'Động vật',
    'missions.join': 'Tham gia nhiệm vụ',
    'missions.leave': 'Rời nhiệm vụ',
    'missions.participants': 'người tham gia',
    'missions.region': 'Khu vực',
    'missions.allRegions': 'Tất cả khu vực',
    'missions.difficulty.easy': 'Dễ',
    'missions.difficulty.medium': 'Trung bình',
    'missions.difficulty.hard': 'Khó',
    // Profile
    'profile.title': 'Hồ sơ',
    'profile.edit': 'Chỉnh sửa hồ sơ',
    'profile.save': 'Lưu thay đổi',
    'profile.cancel': 'Hủy',
    'profile.personalInfo': 'Thông tin cá nhân',
    'profile.fullName': 'Họ tên',
    'profile.email': 'Địa chỉ email',
    'profile.phone': 'Số điện thoại',
    'profile.city': 'Thành phố/Nơi cư trú',
    'profile.language': 'Cài đặt ngôn ngữ',
    'profile.interests': 'Sở thích tình nguyện',
    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Đã xảy ra lỗi',
    'common.retry': 'Thử lại',
    'common.close': 'Đóng',
    'common.back': 'Quay lại',
    // Auth
    'auth.title': 'Đăng nhập KindWorld',
    'auth.subtitle': 'Biến lòng tốt thành tác động',
    'auth.chooseAccount': 'Chọn loại tài khoản của bạn:',
    'auth.signInWith': 'Đăng nhập KindWorld bằng Gmail',
    'auth.signingIn': 'Đang đăng nhập...',
    'auth.roleStudent': 'Đăng nhập là Sinh viên',
    'auth.roleStudentDesc': 'Tôi là sinh viên muốn tình nguyện và theo dõi giờ của mình',
    'auth.roleCompany': 'Đăng nhập là Công ty',
    'auth.roleCompanyDesc': 'Tôi đại diện cho công ty hỗ trợ các chương trình tình nguyện',
    'auth.roleNGO': 'Đăng nhập là NGO',
    'auth.roleNGODesc': 'Tôi là NGO tạo nhiệm vụ và xác minh công việc tình nguyện',
    'auth.demoMode': 'Chế độ Demo',
    'auth.demoInstruction': 'Nhấp vào nút trên để đăng nhập với tư cách',
    'auth.successTitle': 'Xác thực thành công! 🎉',
    'auth.redirecting': 'Đang chuyển hướng đến',
    'auth.dashboard': 'bảng điều khiển',
    'auth.student': 'sinh viên',
    'auth.company': 'công ty',
    'auth.ngo': 'NGO',
    'auth.termsAgree': 'Bằng cách tiếp tục, bạn đồng ý với',
    'auth.termsOfService': 'Điều khoản Dịch vụ',
    'auth.and': 'và',
    'auth.privacyPolicy': 'Chính sách Bảo mật'
  },
  ko: {
    // Navigation
    'nav.home': '홈',
    'nav.missions': '미션',
    'nav.badges': '배지',
    'nav.leaderboard': '리더보드',
    'nav.profile': '프로필',
    // Dashboard
    'dashboard.volunteerHours': '완료된 봉사 시간',
    'dashboard.growth': '전월 대비',
    'dashboard.viewBadges': '배지 및 마일스톤 보기',
    'dashboard.hoursStatement': '봉사 시간 명세서',
    'dashboard.leaderboard': '리더보드',
    'dashboard.viewAll': '모두 보기',
    'dashboard.you': '나',
    'dashboard.hours': '시간',
    'dashboard.dataFor': '데이터',
    // Stats
    'stats.totalHours': '총 시간',
    'stats.projects': '완료된 프로젝트',
    'stats.organizations': '도움을 준 조직',
    'stats.rating': '평균 평점',
    'stats.thisMonth': '이번 달',
    // Badges
    'badges.title': '배지 및 마일스톤',
    'badges.description': '봉사 시간에 따라 인증서, 메달 및 마일스톤을 획득하세요. 파트너 조직의 공식 인정을 신청하세요.',
    'badges.earned': '획득한 배지',
    'badges.totalHours': '총 시간',
    'badges.nextBadge': '다음 배지까지 남은 시간',
    'badges.allEarned': '모든 배지 획득 완료!',
    'badges.all': '모든 배지',
    'badges.milestones': '마일스톤',
    'badges.certificates': '인증서',
    'badges.medals': '메달',
    'badges.earnedOn': '획득일',
    'badges.applyCertificate': '인증서 신청',
    'badges.claimMedal': '메달 받기',
    'badges.moreHours': '추가 시간 필요',
    // Missions
    'missions.title': '이용 가능한 미션',
    'missions.subtitle': '봉사 미션에 참여하여 지역 사회에 긍정적인 영향을 만드세요',
    'missions.all': '모든 미션',
    'missions.environment': '환경',
    'missions.community': '커뮤니티',
    'missions.healthcare': '의료',
    'missions.education': '교육',
    'missions.animals': '동물',
    'missions.join': '미션 참여',
    'missions.leave': '미션 나가기',
    'missions.participants': '참가자',
    'missions.region': '지역',
    'missions.allRegions': '모든 지역',
    'missions.difficulty.easy': '쉬움',
    'missions.difficulty.medium': '보통',
    'missions.difficulty.hard': '어려움',
    // Profile
    'profile.title': '프로필',
    'profile.edit': '프로필 편집',
    'profile.save': '변경 사항 저장',
    'profile.cancel': '취소',
    'profile.personalInfo': '개인 정보',
    'profile.fullName': '이름',
    'profile.email': '이메일 주소',
    'profile.phone': '전화번호',
    'profile.city': '도시/거주지',
    'profile.language': '언어 설정',
    'profile.interests': '봉사 관심사',
    // Common
    'common.loading': '로딩 중...',
    'common.error': '오류가 발생했습니다',
    'common.retry': '다시 시도',
    'common.close': '닫기',
    'common.back': '뒤로',
    // Auth
    'auth.title': 'KindWorld 로그인',
    'auth.subtitle': '친절을 영향력으로 바꾸세요',
    'auth.chooseAccount': '계정 유형을 선택하세요:',
    'auth.signInWith': 'Gmail로 KindWorld 로그인',
    'auth.signingIn': '로그인 중...',
    'auth.roleStudent': '학생으로 로그인',
    'auth.roleStudentDesc': '봉사 활동을 하고 시간을 추적하고 싶은 학생입니다',
    'auth.roleCompany': '회사로 로그인',
    'auth.roleCompanyDesc': '봉사 프로그램을 지원하는 회사를 대표합니다',
    'auth.roleNGO': 'NGO로 로그인',
    'auth.roleNGODesc': '미션을 만들고 봉사 활동을 검증하는 NGO입니다',
    'auth.demoMode': '데모 모드',
    'auth.demoInstruction': '위 버튼을 클릭하여 로그인하세요',
    'auth.successTitle': '인증 성공! 🎉',
    'auth.redirecting': '이동 중',
    'auth.dashboard': '대시보드',
    'auth.student': '학생',
    'auth.company': '기업',
    'auth.ngo': 'NGO',
    'auth.termsAgree': '계속 진행하면 다음에 동의하는 것입니다',
    'auth.termsOfService': '서비스 이용약관',
    'auth.and': '및',
    'auth.privacyPolicy': '개인정보 처리방침'
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.missions': 'Missionen',
    'nav.badges': 'Abzeichen',
    'nav.leaderboard': 'Rangliste',
    'nav.profile': 'Profil',
    // Dashboard
    'dashboard.volunteerHours': 'Absolvierte Freiwilligenstunden',
    'dashboard.growth': 'im Monatsvergleich',
    'dashboard.viewBadges': 'Abzeichen & Meilensteine anzeigen',
    'dashboard.hoursStatement': 'Freiwilligenstunden-Bericht',
    'dashboard.leaderboard': 'Rangliste',
    'dashboard.viewAll': 'Alle anzeigen',
    'dashboard.you': 'Du',
    'dashboard.hours': 'Stunden',
    'dashboard.dataFor': 'Daten für',
    // Stats
    'stats.totalHours': 'Gesamtstunden',
    'stats.projects': 'Abgeschlossene Projekte',
    'stats.organizations': 'Unterstützte Organisationen',
    'stats.rating': 'Durchschnittliche Bewertung',
    'stats.thisMonth': 'diesen Monat',
    // Badges
    'badges.title': 'Abzeichen & Meilensteine',
    'badges.description': 'Verdienen Sie Zertifikate, Medaillen und Meilensteine basierend auf Ihren Freiwilligenstunden. Beantragen Sie offizielle Anerkennung von Partnerorganisationen.',
    'badges.earned': 'Verdiente Abzeichen',
    'badges.totalHours': 'Gesamtstunden',
    'badges.nextBadge': 'Stunden bis zum nächsten Abzeichen',
    'badges.allEarned': 'Alle Abzeichen verdient!',
    'badges.all': 'Alle Abzeichen',
    'badges.milestones': 'Meilensteine',
    'badges.certificates': 'Zertifikate',
    'badges.medals': 'Medaillen',
    'badges.earnedOn': 'Verdient am',
    'badges.applyCertificate': 'Zertifikat beantragen',
    'badges.claimMedal': 'Medaille einlösen',
    'badges.moreHours': 'weitere Stunden benötigt',
    // Missions
    'missions.title': 'Verfügbare Missionen',
    'missions.subtitle': 'Nehmen Sie an Freiwilligenmissionen teil und schaffen Sie einen positiven Einfluss in Ihrer Gemeinde',
    'missions.all': 'Alle Missionen',
    'missions.environment': 'Umwelt',
    'missions.community': 'Gemeinschaft',
    'missions.healthcare': 'Gesundheit',
    'missions.education': 'Bildung',
    'missions.animals': 'Tiere',
    'missions.join': 'Mission beitreten',
    'missions.leave': 'Mission verlassen',
    'missions.participants': 'Teilnehmer',
    'missions.region': 'Region',
    'missions.allRegions': 'Alle Regionen',
    'missions.difficulty.easy': 'Einfach',
    'missions.difficulty.medium': 'Mittel',
    'missions.difficulty.hard': 'Schwer',
    // Profile
    'profile.title': 'Profil',
    'profile.edit': 'Profil bearbeiten',
    'profile.save': 'Änderungen speichern',
    'profile.cancel': 'Abbrechen',
    'profile.personalInfo': 'Persönliche Informationen',
    'profile.fullName': 'Vollständiger Name',
    'profile.email': 'E-Mail-Adresse',
    'profile.phone': 'Telefonnummer',
    'profile.city': 'Stadt/Wohnort',
    'profile.language': 'Spracheinstellungen',
    'profile.interests': 'Freiwilligeninteressen',
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.retry': 'Erneut versuchen',
    'common.close': 'Schließen',
    'common.back': 'Zurück',
    // Auth
    'auth.title': 'Bei KindWorld anmelden',
    'auth.subtitle': 'Verwandeln Sie Freundlichkeit in Wirkung',
    'auth.chooseAccount': 'Wählen Sie Ihren Kontotyp:',
    'auth.signInWith': 'Mit Gmail bei KindWorld anmelden',
    'auth.signingIn': 'Anmeldung...',
    'auth.roleStudent': 'Als Student anmelden',
    'auth.roleStudentDesc': 'Ich bin ein Student, der sich ehrenamtlich engagieren und meine Stunden verfolgen möchte',
    'auth.roleCompany': 'Als Unternehmen anmelden',
    'auth.roleCompanyDesc': 'Ich vertrete ein Unternehmen, das Freiwilligenprogramme unterstützt',
    'auth.roleNGO': 'Als NGO anmelden',
    'auth.roleNGODesc': 'Ich bin eine NGO, die Missionen erstellt und Freiwilligenarbeit verifiziert',
    'auth.demoMode': 'Demo-Modus',
    'auth.demoInstruction': 'Klicken Sie oben auf die Schaltfläche, um sich anzumelden als',
    'auth.successTitle': 'Authentifizierung erfolgreich! 🎉',
    'auth.redirecting': 'Weiterleitung zu Ihrem',
    'auth.dashboard': 'Dashboard',
    'auth.student': 'Student',
    'auth.company': 'Unternehmen',
    'auth.ngo': 'NGO',
    'auth.termsAgree': 'Durch Fortfahren stimmen Sie unseren',
    'auth.termsOfService': 'Nutzungsbedingungen',
    'auth.and': 'und',
    'auth.privacyPolicy': 'Datenschutzrichtlinie'
  }
}

const initialState: LanguageState = {
  currentLanguage: 'en',
  translations
}

const languageSlice = createSlice({
  name: 'language',
  initialState,
  reducers: {
    setLanguage: (state, action: PayloadAction<string>) => {
      state.currentLanguage = action.payload
    }
  }
})

export const { setLanguage } = languageSlice.actions
export default languageSlice.reducer